language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm

matrix:
  allow_failures:
    - php: 5.5
    - php: hhvm

before_install:
  - composer self-update
  - composer clear-cache

install: composer install

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
